[tool.poetry]
name = "codem"
version = "0.1.0"
description = ""
authors = ["user <user@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pyyaml = "^6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
